#+TITLE: PSCHOANALYTIC CASE STUDIES FROM SIGMUND FREUD
#+AUTHOR: Divya Ranjan
#+HTML_HEAD: <link rel="stylesheet"  type="text/css" href="https://cdn.simplecss.org/simple.min.css" />
#+OPTIONS: :section-numbers nil  :with-toc nil

This website maintains the relevant chronological and bibliographical literature assosciated witht the clinical cases that Freud treated during his lifetime, alongwith the secondary literature surrounding interpretations from various psychoanalytic schools.

* Foreword
Sigmund Freud, the man behind the whole psychoanalytic movement, started his journey originally as a medical professional and specializing in neurology. But after several interventions and trials he was more and more interested in psychiatry. He traveled several places and was introduced to several leading figures of his time, including Charcot in Paris where his contemporary, Pierre Janet. While he didn't have the chance to work closely with Charcot as Janet, it was Josef Breuer who took Freud's interests and work seriously and gave him the break which would go on to define the very beginnings of psychoanalysis. Freud and Breuer collaborated together for several years, and were primarily working with hysteric women through the various methodologies such as hypnosis, pressure technique etc. And during this project, both Breuer and Freud started to make little discoveries about the workings of psyche from these hysterics that would be central to how psychoanalysis went on to describe the psyche and its various facets. During this "hysteric project" the duo unearthed many concepts such as free assosciation, psychosomatic symptoms, defence mechanisms, speech and its relation to symptoms and a whole repertoire of conceptualizations that was hidden to mankind till then. It is far from exaggeration to claim that if the study of these hysterics would've never occured then the way we speak to each other today, in modern parlance, would be much different than how it is today.

While, of course, Freud was the physician for these hysterics, he was not /just/ playing that role. Freud was indeed actively learning from his patients, and this was probably the very first time we saw something like this happening in the fielf of medicine, psychiatry and psychopathology. By allowing the hysterics to describe their experiences, traumatic memories, feelings and relating them with the somatic symptoms, Freud was going beyond just getting rid of symptoms, he was trying to understand what reality was like, for those women. And in this process of allowing the patients to speak, feel and assosciate lies the central core of Freudian psychoanalysis, that of /free assosciation/. If there's anything that one could use to be a truly "dogmatic Freudian" then it is this: the insistence to radical extents on free assosciation, and the way the patient reformulates herself in her speech. And it is here, in my opinion, where lies the whole Lacanian movement of "return to Freud". And this comes as no shock that in one of his lectures that Lacan gave at Belgium in 1977 titled /Propos Sur L'Hysterie (Remarks on Hysteria)/. He starts by saying:

#+begin_quote
… Where have they gone, the hysterics of yesteryear, those marvelous women, the Anna O.'s, the Emmy von N's . . . ? Not only did they play a certain social role, but *when Freud took to listening to them, it was they who permitted the birth of psychoanalysis. It was from listening to them that Freud inaugurated an entirely new mode of human relation.*
#+end_quote

While of course the hysterics and their study was how Freud started his journey, it was not all that he published as case material. Rather ironically it's the hysterics mentioned in the classic /Studies on Hysteria/ that are usually forgotten when talking about Freud's clinical work and most of the attention goes to the other five well-known cases such as Dora, Ratman or Wolfman. I make no such presumptions, while certainly one can talk and critique Freud's writing, understaning or lack thereof one mustn't ignore some cases in preference to others, simply because each case study in itself speaks of Freud's venture into the human psyche. It shows what pathways he chose, how he failed, where he did succeed and most importantly what he showed the world from his venture. All the cases, even the ones that are omitted or scarcely spoken of (e.g Nina, Frau Cacile) are worth studying in detail. Thus here we present the relevant literature with chronology of all the cases, including the ones that have become obscure in psychoanalytic discourses. Beyond being for referential and bibliographic purpose the site intends to remind everyone engaging with psychoanalytic literature the importance of learning from case studies without discarding them as dated.
